server:
  port: 8080

my:
  servers:
  - dev.bar.com
  - foo.bar.com
app:
  exit-on-errors: true
  trade-start-date: 03-25-2016

libo:
  name: rinbo

debug: true

logging:
  level: debug

spring:
  profiles:
    active: product
---

spring:
  profiles: dev
libo:
  name: libo-dev

---
spring:
  profiles: product
libo:
  name: libo-product